project:
  type: website

website:
  title: "Quinty Boer"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - education.qmd
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

